"""ensure users table exists

Revision ID: 20260326_0005
Revises: 20260326_0004
Create Date: 2026-03-26 22:30:00
"""

from alembic import op

revision = "20260326_0005"
down_revision = "20260326_0004"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS app_core")

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS app_core.users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username VARCHAR(100) NOT NULL,
            password_hash VARCHAR(255) NOT NULL,
            role VARCHAR(50),
            is_active BOOLEAN NOT NULL DEFAULT true,
            employee_id INTEGER,
            allowed_pages JSONB,
            google_sub VARCHAR(255),
            legacy_id INTEGER,
            source_system VARCHAR(100),
            imported_at TIMESTAMPTZ,
            updated_at TIMESTAMPTZ NOT NULL
        )
        """
    )

    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_schema = 'app_core'
                  AND table_name = 'employees'
            ) AND NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conname = 'users_employee_id_fkey'
                  AND connamespace = 'app_core'::regnamespace
            ) THEN
                ALTER TABLE app_core.users
                ADD CONSTRAINT users_employee_id_fkey
                FOREIGN KEY (employee_id) REFERENCES app_core.employees(id);
            END IF;
        END
        $$;
        """
    )

    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS ix_app_core_users_username
        ON app_core.users (username)
        """
    )

    op.execute(
        """
        CREATE INDEX IF NOT EXISTS ix_app_core_users_legacy_id
        ON app_core.users (legacy_id)
        """
    )


def downgrade() -> None:
    # Safe downgrade: keep users table to avoid data loss.
    pass
