"""Add InventoryImport models

Revision ID: 0008_inventory_imports
Revises: 20260327_0007_product_unique_cod_produto
Create Date: 2026-03-30 11:00:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0008_inventory_imports'
down_revision: Union[str, None] = '0007_product_unique_cod_produto'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_imports',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('reference_date', sa.Date(), nullable=False),
        sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('total_products', sa.Integer(), nullable=False),
        sa.Column('created_products', sa.Integer(), nullable=False),
        sa.Column('imported_by', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column('imported_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema='app_core'
    )
    op.create_index(op.f('ix_app_core_inventory_imports_reference_date'), 'inventory_imports', ['reference_date'], unique=False, schema='app_core')
    
    op.create_table('inventory_import_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('inventory_import_id', sa.Integer(), nullable=False),
        sa.Column('cod_produto', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('metrics', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['inventory_import_id'], ['app_core.inventory_imports.id'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='app_core'
    )
    op.create_index(op.f('ix_app_core_inventory_import_items_cod_produto'), 'inventory_import_items', ['cod_produto'], unique=False, schema='app_core')
    op.create_index(op.f('ix_app_core_inventory_import_items_inventory_import_id'), 'inventory_import_items', ['inventory_import_id'], unique=False, schema='app_core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_core_inventory_import_items_inventory_import_id'), table_name='inventory_import_items', schema='app_core')
    op.drop_index(op.f('ix_app_core_inventory_import_items_cod_produto'), table_name='inventory_import_items', schema='app_core')
    op.drop_table('inventory_import_items', schema='app_core')
    op.drop_index(op.f('ix_app_core_inventory_imports_reference_date'), table_name='inventory_imports', schema='app_core')
    op.drop_table('inventory_imports', schema='app_core')
    # ### end Alembic commands ###
